title: "Site de MlleStrife"
description: "Réflexions sur l'informatique, analyses et retours d’expérience autour de l’intelligence artificielle  & formation en cybersécurité."
remote_theme: pages-themes/architect@v0.2.0
theme: jekyll-theme-cayman
author: "MlleStrife"
plugins:
- jekyll-remote-theme

markdown: kramdown